FORMAT: 1A
HOST: http://api.staging.cherehapa.ru/v2

# API проекта "Черехапа Страхование" v2.0 - Расчет и выписка полиса

## Параметры для создания полиса
При расчете полиса автоматически создается запрос (request), который можно использовать в дальнейшем для выписки страхового полиса. Если есть id запроса, то достаточно передать его параметром requestId вместо всех условий запроса. Если при формировании запроса на расчет не были указаны данные туристов, то их лучше передать вместе с requestId - в этом случае запрос в БД будет обновлен данными из HTTP-запроса.

Эти **обязательные** и *необязательные* параметры используются для создания полиса.

- **dateStart** - дата начала поездки - дата в формате dd.mm.yyyy (22.03.2015)
- **dateEnd** - дата окончания поездки - дата в формате dd.mm.yyyy (25.03.2015)
- **country[]** - код или id одной или нескольких стран путешествия - массив строк или массив чисел (количество не ограниченно)
- *countryGroup[]* - код или id группы стран - массив строк или массив чисел (schengen, asia)
- *sport[]* - коды видов спортивной активности - массив строк или массив чисел (surfing, divingCompetition)
- **insuranceProduct[]** - массив кодов страховых продуктов - число или массив чисел (1, 57)
- **service[<код услуги>]** - коды и значения страховых сумм поивыбранным услугам - число (service[medicine]=30000, service[legal]=1)
- **insurer** - массив данных о покупателе полиса - строка (страхователе)
- **insurer[name]** - имя страхователя - строка (Alexander)
- **insurer[lastName]** - фамилия страхователя - строка (Pavlov)
- **insurer[email]** - электронная почта страхователя - строка (ap@tsys.pw)
- *insurer[phone]* - телефон страхователя в международном формате, без "+" - строка (79264240454)
- **tourist[]** - массив данных о туристах - строка
- **tourist[#][firstName]** - имя туриста - строка (Alexander)
- **tourist[#][lastName]** - фамилия туриста - строка (Pavlov)
- **tourist[#][birthday]** - дата рождения туриста - дата в формате dd.mm.yyyy (31.12.1982)
- *tourist[#][age]* - возраст туриста - число (можно указывать, когда не известна точная дата рождения)
- *paymentSystem* - код платежной системы - число (для безналичной оплаты paymentSystem=8)
- *currency* - код валюты страхования - строка (USD, EUR, RUB, по-умолчанию - USD)
- *card* - массив данных о банковской карте пользователя - строка (нужен только в том случае, когда выбрана соответствующая платежная система).
- *card[number]* - номер банковской карты - строка (4111111111111111)
- *card[cvc]* - код безопасности карты - число (123)
- *card[month]* - месяц окончания срока действия карты - число (12)
- *card[year]* - год окончания срока действия карты - число (15)
- *card[holder]* - фамилия и имя держателя карты - строка (Alexander Pavlov)


Расчёт стоимости страховых продуктов Для расчета стоимости страховых продуктов необходимо отправить GET-запрос:
~~по адресу /quote (для расчета всех продуктов) или /quote/id~~


## Создает новый запрос [/request/{id}?key={key}]

+ Parameters
    + id: `3` (optional, number) - id запроса партнера (например 3)
    + key: yI99Kone4QHOuaPqmgpp7WoTmW0cDs (required, string) - Ключ доступа (служит для авторизации, при изменении перестает работать)

### Метод: GET /request [GET]

Выводится список запросов, сделанных партнером. В примере дана только первая запись из всего списка. Для получения всего списка, выполните запрос.
+ Response 200 (application/json)

            {
             "status": 200,

            }